parameters:
  - name: sonarKey
    type: string

jobs:
  - job: BuildAndTest
    steps:
      - checkout: self
        persistCredentials: true
      - task: FlutterInstall@0
        displayName: 'Installation Flutter'
        inputs:
          mode: 'auto'
          channel: 'stable'
      - task: shellexec@0
        displayName: 'Installation Dart'
        inputs:
          code: |
            sudo wget https://dl-ssl.google.com/linux/linux_signing_key.pub -O - | sudo apt-key add -
            sudo wget https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list -O /etc/apt/sources.list.d/dart_stable.list
            sudo apt-get update
            sudo apt-get install dart
      - task: FlutterCommand@0
        displayName: 'Cider Activation'
        inputs:
          projectDirectory: './src/'
          arguments: 'pub global activate cider'
      
      - bash: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          cd /home/vsts/work/1/s/src/
          VERSION_TAG=`cider version` && echo "##vso[task.setvariable variable=releaseVersion]$VERSION_TAG"
        displayName: 'Getting actual version'


      - task: CmdLine@1
        displayName: 'Version tag creation'
        inputs:
          filename: sh
          arguments: -c "echo \"##vso[task.setvariable variable=imageTag]$(Build.SourceBranchName)-$(releaseVersion)\"
          
      - task: SonarQubePrepare@5
        displayName: 'Prepare Sonar'
        inputs:
          SonarQube: 'Sonar'
          scannerMode: 'CLI'
          configMode: 'manual'
          cliProjectKey: ${{ parameters.sonarKey }}
          cliSources: '.'
          cliProjectName: $(Build.Repository.Name)
          extraProperties: |
            sonar.exclusions=/coveragereport/**
            sonar.flutter.coverage.reportPath=/home/vsts/work/1/s/src/coverage/lcov.info
            sonar.projectVersion=$(imageTag)
            sonar.sources=/home/vsts/work/1/s/src/lib 
            sonar.c.file.suffixes=-
            sonar.cpp.file.suffixes=-
            sonar.objc.file.suffixes=-
        
      - task: PowerShell@2
        displayName: 'Setup environment'
        inputs:
          targetType: 'inline'
          script: |
            Write-Host "##vso[task.prependpath]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.setvariable variable=JAVA_HOME;]$(JAVA_HOME_11_X64)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)"
            Write-Host "##vso[task.prependpath]$(FlutterToolPath)/cache/dart-sdk/bin"
      - task: FlutterBuild@0
        displayName: 'Build project for web'
        inputs:
          target: 'web'
          projectDirectory: './src/'

      - task: FlutterTest@0
        displayName: 'Test project'
        inputs:
          projectDirectory: './src/'
          generateCodeCoverageReport: true
          
      - task: SonarQubeAnalyze@5
        displayName: 'Sonar analyse'

      - task: SonarQubePublish@5
        displayName: 'Sonar publish'
        inputs:
          pollingTimeoutSec: '300'
            
      - task: reportgenerator@5
        displayName: 'Generating test report'
        inputs:
          reports: './src/coverage/lcov.info'
          targetdir: './coveragereport'
          sourcedirs: './src/'

      - task: PublishCodeCoverageResults@1
        displayName: 'Publish test result'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: './coveragereport/Cobertura.xml'
          reportDirectory: './coveragereport'
          pathToSources: './src/'

      - task: CopyFiles@2
        inputs:
          SourceFolder: '/home/vsts/work/1/s/src'
          Contents: '**'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'