parameters:
  - name: environment
    type: string
  - name: firebaseToken
    type: string

jobs:
  - job: BuildAndDeploy
    steps:
      - checkout: self
        persistCredentials: true
      - task: FlutterInstall@0
        displayName: 'Installation Flutter'
        inputs:
          mode: 'auto'
          channel: 'stable'
      - task: shellexec@0
        displayName: 'Installation Dart'
        inputs:
          code: |
            sudo wget https://dl-ssl.google.com/linux/linux_signing_key.pub -O - | sudo apt-key add -
            sudo wget https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list -O /etc/apt/sources.list.d/dart_stable.list
            sudo apt-get update
            sudo apt-get install dart
      - task: FlutterCommand@0
        displayName: 'Cider Activation'
        inputs:
          projectDirectory: './src/'
          arguments: 'pub global activate cider'

      - bash: |
          export PATH="$PATH":"$HOME/.pub-cache/bin"
          cd /home/vsts/work/1/s/src/
          VERSION_TAG=`cider version` && echo "##vso[task.setvariable variable=releaseVersion]$VERSION_TAG"
        displayName: 'Getting actual version'

      - task: CmdLine@1
        displayName: 'Version tag creation'
        inputs:
          filename: sh
          arguments: -c "echo \"##vso[task.setvariable variable=imageTag]$(Build.SourceBranchName)-$(releaseVersion)\"
        
  - deployment:
    displayName: Deploiement ${{ parameters.environment }}
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'drop'
                targetPath: '$(Pipeline.Workspace)'
            - task: NodeTool@0
              inputs:
                versionSource: 'spec'
                versionSpec: '18.x'
              displayName: Install Node

            - task: shellexec@0
              displayName: Set Environment Config
              inputs:
                code: |
                  cd $(Pipeline.Workspace)/tools/
                  node environment-generator ${{ parameters.environment }}
            
            - script: |
                npm install -g firebase-tools
                echo $TOKEN > $HOME/gcloud.json
                export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
                firebase deploy --only hosting
              displayName: 'firebase publish'
              env:
                TOKEN: ${{ parameters.firebaseToken }}
