name: Dotnet core Action
on:
  workflow_dispatch:
    input:
      

jobs:
  initialisation:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-init-${{github.ref}}
      cancel-in-progress: true
    uses: /jobs/initialisation.yml@master
    with:
      versionIncrement: 