parameters:
  - name: sonarKey
    type: string
    default: ''
  - name: javaVersion
    type: string
  - name: projectVersion
    type: string
  - name: jsonFile
    type: string
  - name: sonarConnection
    type: string
    default: Sonar

jobs:
  - job: Build_Test
    timeoutInMinutes: 30
    steps:
    - checkout: self
      clean: true
      persistCredentials: true
    - template: ..\..\steps\set_version_file.yml
      parameters:
        jsonFile: ${{parameters.jsonFile}}
        releaseVersion: ${{parameters.projectVersion}}
    - ${{ if ne(parameters.sonarKey, '') }}:
      - task: SonarQubePrepare@5
        inputs:
          SonarQube: '${{ parameters.sonarConnection }}'
          scannerMode: 'Other'
          extraProperties: |
            sonar.projectKey=${{ parameters.sonarKey }}
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: ${{ parameters.javaVersion }}
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    - task: Cache@2
      displayName: 'Cache Gradle packages'
      inputs:
        key: 'gradle | "$(Agent.OS)" | **/build.gradle'
        restoreKeys: 'gradle | "$(Agent.OS)"'
        path: '$(GRADLE_USER_HOME)/caches'
    - task: Gradle@3
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        ${{ if ne(parameters.sonarKey, '') }}:
          sonarQubeRunAnalysis: true
          sqGradlePluginVersionChoice: 'specify'
          sonarQubeGradlePluginVersion: '2.6.1'
          spotBugsAnalysis: false

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)'
        artifact: 'drop'
        publishLocation: 'pipeline'
    - ${{ if ne(parameters.sonarKey, '') }}:
      - task: SonarQubePublish@5
        inputs:
          pollingTimeoutSec: '300'
