trigger:
  - master

parameters:
  - name: versionIncrement
    type: string
    default: 'patch'
  - name: sonarKey
    type: string
  - name: securityTargetDir
    type: string
  - name: projectFile
    type: string
  - name: jsonFile
    type: string

stages:
  #Initialization
  - stage: Initialization
    jobs:
      - template: /jobs/json_semantic_version.yml
        parameters:
          versionIncrement: ${{ parameters.versionIncrement }}
          jsonFile: ${{ parameters.jsonFile }}
          
  - stage: BuildAndTest
    displayName: 'Build Test and Sonar'
    dependsOn: Initialization
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    jobs:
      - template: /jobs/dotnetcore/dotnetcore_build_test.yml
        parameters:
          sonarProjectKey: ${{parameters.sonarKey}}
          projectFile: ${{ parameters.projectFile }}
          projectVersion: $(version)
  
  - stage: Finalization
    displayName: 'Finalization'
    dependsOn:
      - Initialization
      - BuildAndTest
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    jobs:
      - template: /jobs/finalisation.yml
        parameters:
          releaseVersion: $(version)
          jsonFile: ${{ parameters.jsonFile }}
          language: '.net'