trigger:
  - master

parameters:
  - name: versionIncrement
    type: string
    default: 'patch'
  - name: gitFlowType
    displayName: Git flow strategy
    type: string
    default: github-flow
    values:
      - github-flow
      - gitflow
      - trunk-based
      - gitlab-flow
  - name: developIncrement
    displayName: Version increment for develop branch (gitflow)
    type: string
    default: patch
  - name: releaseIncrement
    displayName: Version increment for release branches (gitflow)
    type: string
    default: minor
  - name: hotfixIncrement
    displayName: Version increment for hotfix branches (gitflow)
    type: string
    default: patch
  - name: sonarKey
    type: string
  - name: securityTargetDir
    type: string
  - name: projectFile
    type: string
  - name: jsonFile
    type: string

stages:
  - stage: Initialization
    jobs:
      - template: /jobs/json_semantic_version.yml
        parameters:
          versionIncrement: ${{ parameters.versionIncrement }}
          jsonFile: ${{ parameters.jsonFile }}
          gitFlowType: ${{ parameters.gitFlowType }}
          developIncrement: ${{ parameters.developIncrement }}
          releaseIncrement: ${{ parameters.releaseIncrement }}
          hotfixIncrement: ${{ parameters.hotfixIncrement }}

  - stage: BuildAndTest
    displayName: 'Build Test and Sonar'
    dependsOn: Initialization
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    jobs:
      - template: /jobs/dotnetcore/dotnetcore_build_test.yml
        parameters:
          sonarProjectKey: ${{parameters.sonarKey}}
          projectFile: ${{ parameters.projectFile }}
          projectVersion: $(version)

  - stage: Finalization
    displayName: 'Finalization'
    condition: and(succeeded(), eq(dependencies.Initialization.outputs['Versioning.gitflow.shouldFinalize'], 'true'))
    dependsOn:
      - Initialization
      - BuildAndTest
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
      shouldTag: $[stageDependencies.Initialization.Versioning.outputs['gitflow.shouldTag']]
    jobs:
      - template: /jobs/finalisation.yml
        parameters:
          releaseVersion: $(version)
          jsonFile: ${{ parameters.jsonFile }}
          language: '.net'
          shouldTag: $(shouldTag)