trigger:
  - master

parameters:
  - name: appName
    displayName: Application name
    type: string
    default: $(Build.Repository.Name)
  - name: jsonFile
    type: string
    default: cicd.json
  - name: versionIncrement
    type: string
    default: 'patch'
  - name: gitFlowType
    displayName: Git flow strategy
    type: string
    default: github-flow
    values:
      - github-flow
      - gitflow
      - trunk-based
      - gitlab-flow
  - name: gradlePath
    type: string
  - name: sonarKey
    type: string
  - name: javaVersion
    type: string
  - name: dockerRegistry
    type: string
  - name: containerRegistry
    type: string

stages:
  - stage: Initialization
    jobs:
      - template: /jobs/json_semantic_version.yml
        parameters:
          versionIncrement: ${{ parameters.versionIncrement }}
          jsonFile: ${{ parameters.jsonFile }}
          gitFlowType: ${{ parameters.gitFlowType }}
  - stage: Build_And_Test
    dependsOn: Initialization
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    jobs:
      - template: /jobs/java/java_gradle_test_and_build.yml
        parameters:
          sonarKey: ${{ parameters.sonarKey }}
          javaVersion: ${{ parameters.javaVersion }}
          projectVersion: $(version)
          jsonFile: ${{ parameters.jsonFile }}
  - stage: Docker_Build_And_Publish
    condition: and(succeeded(), eq(dependencies.Initialization.outputs['Versioning.gitflow.shouldDeploy'], 'true'))
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    dependsOn:
      - Initialization
      - Build_And_Test
    jobs:
      - template: /jobs/docker_build_and_publish.yml
        parameters:
          registry: ${{ parameters.dockerRegistry }}
          containerRegistry: ${{ parameters.containerRegistry }}
          projectVersion: $(version)

  - stage: Finalization
    condition: and(succeeded(), eq(dependencies.Initialization.outputs['Versioning.gitflow.shouldFinalize'], 'true'))
    dependsOn:
      - Initialization
      - Build_And_Test
      - Docker_Build_And_Publish
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
      shouldTag: $[stageDependencies.Initialization.Versioning.outputs['gitflow.shouldTag']]
    jobs:
      - template: /jobs/finalisation.yml
        parameters:
          releaseVersion: $(version)
          jsonFile: ${{ parameters.jsonFile }}
          language: 'java'
          shouldTag: $(shouldTag)

  - stage: Deploy
    condition: and(succeeded(), eq(dependencies.Initialization.outputs['Versioning.gitflow.shouldDeploy'], 'true'))
    dependsOn:
      - Initialization
      - Build_And_Test
      - Docker_Build_And_Publish
    variables:
      BUILDID: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
      deployEnv: $[stageDependencies.Initialization.Versioning.outputs['gitflow.deployEnvironment']]
    jobs:
      - template: /jobs/kube_deploy.yml
        parameters:
          env: $(deployEnv)
          resource: ${{ parameters.appName }}
          namespace: ${{ parameters.appName }}
    
