trigger:
  - master

parameters:
  - name: appName
    displayName: Application name
    type: string
    default: $(Build.Repository.Name)
  - name: jsonFile
    type: string
    default: cicd.json
  - name: versionIncrement
    type: string
    default: 'patch'
  - name: gitFlowType
    displayName: Git flow strategy
    type: string
    default: github-flow
    values:
      - github-flow
      - gitflow
      - trunk-based
      - gitlab-flow
  - name: developIncrement
    displayName: Version increment for develop branch (gitflow)
    type: string
    default: patch
  - name: releaseIncrement
    displayName: Version increment for release branches (gitflow)
    type: string
    default: minor
  - name: hotfixIncrement
    displayName: Version increment for hotfix branches (gitflow)
    type: string
    default: patch
  - name: gradlePath
    type: string
  - name: javaVersion
    type: string

stages:
  - stage: Initialization
    jobs:
      - template: /jobs/json_semantic_version.yml
        parameters:
          versionIncrement: ${{ parameters.versionIncrement }}
          jsonFile: ${{ parameters.jsonFile }}
          gitFlowType: ${{ parameters.gitFlowType }}
          developIncrement: ${{ parameters.developIncrement }}
          releaseIncrement: ${{ parameters.releaseIncrement }}
          hotfixIncrement: ${{ parameters.hotfixIncrement }}
  - stage: Build
    dependsOn: Initialization
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    jobs:
      - template: /jobs/java/java_gradle_avro_build.yml
        parameters:
          javaVersion: ${{ parameters.javaVersion }}
          projectVersion: $(version)
          jsonFile: ${{ parameters.jsonFile }}
  - stage: Publish_Artifact
    dependsOn:
      - Initialization
      - Build
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    jobs:
      - template: /jobs/java/gradle_package_publish.yml
        parameters:
          javaVersion: ${{ parameters.javaVersion }}
          projectVersion: $(version)
          jsonFile: ${{ parameters.jsonFile }}

  - stage: Finalization
    condition: and(succeeded(), eq(dependencies.Initialization.outputs['Versioning.gitflow.shouldFinalize'], 'true'))
    dependsOn:
      - Initialization
      - Build
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
      shouldTag: $[stageDependencies.Initialization.Versioning.outputs['gitflow.shouldTag']]
    jobs:
      - template: /jobs/finalisation.yml
        parameters:
          releaseVersion: $(version)
          jsonFile: ${{ parameters.jsonFile }}
          language: 'java'
          shouldTag: $(shouldTag)