trigger:
  - master

parameters:
  - name: appName
    displayName: Application name
    type: string
    default: $(Build.Repository.Name)
  - name: jsonFile
    type: string
    default: cicd.json
  - name: versionIncrement
    type: string
    default: 'patch'
  - name: gradlePath
    type: string
  - name: sonarKey
    type: string
  - name: javaVersion
    type: string
  - name: dockerRegistry
    type: string
  - name: containerRegistry
    type: string

stages:
  - stage: Initialization
    jobs:
      - template: /jobs/json_semantic_version.yml
        parameters:
          versionIncrement: ${{ parameters.versionIncrement }}
          jsonFile: ${{ parameters.jsonFile }}
  - stage: Build_And_Test
    dependsOn: Initialization
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    jobs:
      - template: /jobs/java/java_gradle_test_and_build.yml
        parameters:
          sonarKey: ${{ parameters.sonarKey }}
          javaVersion: ${{ parameters.javaVersion }}
          projectVersion: $(version)
          jsonFile: ${{ parameters.jsonFile }}
  - stage: Docker_Build_And_Publish
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    dependsOn: 
      - Initialization
      - Build_And_Test
    jobs:
      - template: /jobs/docker_build_and_publish.yml
        parameters:
          registry: ${{ parameters.dockerRegistry }}
          containerRegistry: ${{ parameters.containerRegistry }}
          projectVersion: $(version)

  - stage: Finalization
    condition: ne(variables['Build.Reason'], 'PullRequest')
    dependsOn: 
      - Initialization
      - Build_And_Test
      - Docker_Build_And_Publish
    variables:
      version: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    jobs:
      - template: /jobs/finalisation.yml
        parameters:
          releaseVersion: $(version)
          jsonFile: ${{ parameters.jsonFile }}
          language: 'java'

  - stage: Deploy_To_Dev
    condition: ne(variables['Build.Reason'], 'PullRequest')
    dependsOn: 
      - Initialization
      - Build_And_Test
      - Docker_Build_And_Publish
    variables:
      BUILDID: $[stageDependencies.Initialization.Versioning.outputs['version.DockerTag']]
    jobs:
      - template: /jobs/kube_deploy.yml
        parameters:
          env: "Dev"
          resource: ${{ parameters.appName }}
          namespace: ${{ parameters.appName }}
    
