parameters:
  - name: registry
    type: string
  - name: projectVersion
    type: string
  - name: containerRegistry
    type: string
  - name: insecureRegistryUrl
    type: string
    default: ''

jobs:
  - job: build_image
    steps:
      - download: current
        artifact: drop
      - bash: cp -rf $(Pipeline.Workspace)/drop/* ./
      - ${{ if ne(parameters.insecureRegistryUrl, '') }}:
        - script: |
            echo '{  "insecure-registries" : ["${{ parameters.insecureRegistryUrl }}"]}' | sudo tee /etc/docker/daemon.json
            sudo service docker restart

      - task: Docker@2
        inputs:
          containerRegistry: '${{ parameters.containerRegistry }}'
          repository: '${{parameters.registry}}'
          command: 'buildAndPush'
          Dockerfile: '$(Pipeline.Workspace)/drop/Dockerfile'
          tags: ${{parameters.projectVersion}}
