parameters:
  - name: registry
    type: string
  - name: projectVersion
    type: string

jobs:
  - job: build_image
    steps:
      - download: current
        artifact: drop
      - bash: cp -rf $(Pipeline.Workspace)/drop/* ./
      - script: |
          echo '{  "insecure-registries" : ["http://141.94.98.187:5000"]}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart

      - task: Docker@2
        inputs:
          containerRegistry: 'minikube'
          repository: '${{parameters.registry}}'
          command: 'buildAndPush'
          Dockerfile: '$(Pipeline.Workspace)/drop/Dockerfile'
          tags: ${{parameters.projectVersion}}
