#Prend en paramètre la variable versionIncrement et le fichier json à mettre à jour
# ce job prend en charge le bump de version, le tag git et le nommage du pipeline dans azure devops
# de plus la version semantic branche-major.minor.patch est persisté dans la variables DockerTag pour les étapes ultérieure
parameters:
  - name: versionIncrement
    type: string
    default: patch
  - name: fichierJson
    type: string

jobs:
  - job: Versionning
    steps:
    - checkout: self
      clean: true
      persistCredentials: true
    - template: ..\steps\set_version_increment.yml
      parameters:
        versionIncrement: ${{ parameters.versionIncrement }}      
    - task: shellexec@0
      displayName: Création du fichier ${{ parameters.fichierJson }} s'il n'existe pas
      inputs:
        code: |
          test -f "$(Build.SourcesDirectory)/${{ parameters.fichierJson }}" || echo "{\"version\": \"0.0.0\"}" > "$(Build.SourcesDirectory)/${{ parameters.fichierJson }}"
          git add ${{ parameters.fichierJson }}
    - task: LoadJsonVariables@2
      displayName: Récupération de la version en cours
      inputs:
        JsonSource: ${{ parameters.fichierJson }}
        VariablePrefix: cicd
        MarkAsSecret: false    
    - task: Npm@1
      displayName: Installation de semver
      inputs:
        command: 'custom'
        customCommand: 'install semver -g'
    - task: CmdLine@1
      displayName: Bump de la version
      inputs:
        filename: sh
        arguments: -c "echo \"##vso[task.setvariable variable=releaseVersion;]`semver $(cicd_version) -i $(versionIncrement)`\"
    - task: CmdLine@1
      displayName: Enregistrement de la version de l'artefact (branch-version)
      inputs:
        filename: sh
        arguments: -c "echo \"##vso[task.setvariable variable=DockerTag;isOutput=true]`node -p '\"$(releaseVersion)\".toLowerCase()'`\"
      name: version
    
    - task: CmdLine@1
      displayName: Mise à jour du nom du pipeline
      inputs:
        filename: sh
        arguments: '-c echo "##vso[build.updatebuildnumber]$(Build.Repository.Name) $(Build.SourceBranchName)-$(releaseVersion)"'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    - task: CmdLine@1
      displayName: Mise à jour du nom du pipeline PR
      inputs:
        filename: sh
        arguments: '-c echo "##vso[build.updatebuildnumber]$(Build.Repository.Name) PR $(System.PullRequest.PullRequestId).$(System.PullRequest.PullRequestIteration)"'
      condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

    - task: CmdLine@1
      displayName: Sauvegarde de la version
      inputs:
        filename: sh
        arguments: -c "echo \"##vso[task.setvariable variable=Version;isOutput=true]$(releaseVersion)\"
      name: semantic