# Takes the versionIncrement variable and the JSON file to update as parameters
# This job handles version bumping, git tagging, and pipeline naming in Azure DevOps
# Additionally, the semantic version branch-major.minor.patch is persisted in the DockerTag variable for subsequent stages
parameters:
  - name: versionIncrement
    type: string
    default: patch
  - name: jsonFile
    type: string

jobs:
  - job: Versioning
    steps:
    - checkout: self
      clean: true
      persistCredentials: true
    - template: ..\steps\set_version_increment.yml
      parameters:
        versionIncrement: ${{ parameters.versionIncrement }}      
    - task: shellexec@0
      displayName: Create file ${{ parameters.jsonFile }} if it does not exist
      inputs:
        code: |
          test -f "$(Build.SourcesDirectory)/${{ parameters.jsonFile }}" || echo "{\"version\": \"0.0.0\"}" > "$(Build.SourcesDirectory)/${{ parameters.jsonFile }}"
          git add ${{ parameters.jsonFile }}
    - task: LoadJsonVariables@2
      displayName: Load current version
      inputs:
        JsonSource: ${{ parameters.jsonFile }}
        VariablePrefix: cicd
        MarkAsSecret: false    
    - task: Npm@1
      displayName: Install semver
      inputs:
        command: 'custom'
        customCommand: 'install semver -g'
    - task: CmdLine@1
      displayName: Bump version
      inputs:
        filename: sh
        arguments: -c "echo \"##vso[task.setvariable variable=releaseVersion;]`semver $(cicd_version) -i $(versionIncrement)`\"
    - task: CmdLine@1
      displayName: Record artifact version (branch-version)
      inputs:
        filename: sh
        arguments: -c "echo \"##vso[task.setvariable variable=DockerTag;isOutput=true]`node -p '\"$(releaseVersion)\".toLowerCase()'`\"
      name: version
    
    - task: CmdLine@1
      displayName: Update pipeline name
      inputs:
        filename: sh
        arguments: '-c echo "##vso[build.updatebuildnumber]$(Build.Repository.Name) $(Build.SourceBranchName)-$(releaseVersion)"'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    - task: CmdLine@1
      displayName: Update PR pipeline name
      inputs:
        filename: sh
        arguments: '-c echo "##vso[build.updatebuildnumber]$(Build.Repository.Name) PR $(System.PullRequest.PullRequestId).$(System.PullRequest.PullRequestIteration)"'
      condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

    - task: CmdLine@1
      displayName: Save version
      inputs:
        filename: sh
        arguments: -c "echo \"##vso[task.setvariable variable=Version;isOutput=true]$(releaseVersion)\"
      name: semantic