parameters:
  - name: jsonFile
    type: string
  - name: releaseVersion
    type: string



steps:
  - task: shellexec@0
    displayName: Create file ${{ parameters.jsonFile }} if it does not exist
    inputs:
      code: |
        test -f "$(Build.SourcesDirectory)/${{ parameters.jsonFile }}" || echo "{\"version\": \"0.0.0\"}" > "$(Build.SourcesDirectory)/${{ parameters.jsonFile }}"
        git add ${{ parameters.jsonFile }}

  - task: JsonPatch@4
    displayName: Update file ${{ parameters.jsonFile }}
    inputs:
      SyntaxType: 'slick'
      JsonWorkingDir: '$(Build.SourcesDirectory)'
      JsonTargetFilters: '${{ parameters.jsonFile }}'
      JsonPatchContent: '= /version => "${{ parameters.releaseVersion}}"'
      OutputPatchFile: true
      TreatErrors: 'ERROR'